### Introduction to SETS in Python
- A set can be thought of as a well-defined collection of distinct objects, typically called elements or members
- set constructor set()
### Libraries- Numpy
- Numerical Python is an open source Python library that's used in almost every field . It is the universal standard for working with numerical data in Python.

In [24]:
set_7 = {1,2,3,4,5}
set_8 = {6,7,8,9,10}

set_7.update(set_8)
print(set_7)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [4]:
# Creating a set
set_1 = {'animals', 'ball', 'cat'}
print(set_1[0])

TypeError: 'set' object is not subscriptable

In [6]:
# No duplication allowed
set_2 = {'animal', 'ball', 'cat', 'animal', 'fish', 'ball'}
set_2

{'animal', 'ball', 'cat', 'fish'}

##### True and 1 are considered the same


In [23]:
set_3 = {'animal', 'ball', 'cat', 'animal', 'fish', 'ball', True, 2,1}
print(set_3)
set_3 .add('bird')
print(set_3)

{True, 2, 'fish', 'ball', 'animal', 'cat'}
{True, 2, 'fish', 'bird', 'ball', 'animal', 'cat'}


##### Cannot add a List and dictionary to a set
- since they are  mutable and makes it unhashable

In [12]:
set_4 = {[1,2,3,4]}
print(set_4) # unhashable 

TypeError: unhashable type: 'list'

In [13]:
set_5 = {(1,2,3,4)}
print(set_5)

{(1, 2, 3, 4)}


##### Nesting is not possible in a set

In [14]:
set_5 = {{1,2,3}, {4,5,6}}
set_5

TypeError: unhashable type: 'set'

##### Creating empty set

In [16]:
empty = set()
print(empty)
print(type(empty))

set()
<class 'set'>


##### Accessing items within a set

In [19]:
a = {'a', 'b', 'c', 'd', 'e'}

for i in a:
    print(i)

e
d
a
b
c


In [21]:
# Code to check if an 'item' is present in the set
set_6 = {'data', 'python', 'code'}

print('code' in set_6)
print('analyst' in set_6)

True
False


##### Join 2 sets

In [25]:
a = {'a', 'b', 'c', 'd', 'e'}
set_6 = {'data', 'python', 'code'}
z = a.union(set_6)
z

{'a', 'b', 'c', 'code', 'd', 'data', 'e', 'python'}

##### Find max and min values

In [28]:
set_n = {5,10,3,15,20,56} 
print('Original set elements')
print(set_n)
print('maximum value in the set:',max(set_n))
print('Minimum value in the set:',min(set_n))

Original set elements
{3, 20, 5, 56, 10, 15}
maximum value in the set: 56
Minimum value in the set: 3


##### Return a new set of identical items from two sets

In [29]:
set_x = {10,20,30,40,50}
set_y = {30,40,50,60,70}

print(set_x.intersection(set_y))

{40, 50, 30}


In [4]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [5]:
arr = np.array((5,6,7,8,9))
arr

array([5, 6, 7, 8, 9])

##### Dimensions in array

In [6]:
arr = np.array(20)
print(arr)
print(arr.ndim) # printing the dimension

20
0


##### 1 D array

In [7]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


##### 2 D array

In [8]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


##### 3 D array

In [9]:
arr = np.array([[[1,2,3], [4,5,6], [6,7,8]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [6 7 8]]]
3


##### Create an array with 5 dimensions and verify that it has 5 dimensions:

In [19]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('number of dimensions: ', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions:  5


##### Numpy Array Indexing

In [10]:
arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [14]:
import numpy
# Get the third , sixth and eighth elements from the following array and sum them
m = np.array([41,87,34,56.8,39.23,90,15,10,19,56])
print('2nd element ', m[2])
print('6th element ', m[5])
print('8th element ', m[7])
print('Sum of the elements ', m[2] + m[5] + m[7])

2nd element  34.0
6th element  90.0
8th element  10.0
Sum of the elements  134.0


##### Indexing 2D arrays

In [17]:
arr = np.array([[1,2,3],[4,5,6]])
print('Second element of 1st row: ', arr[0,1])
print('Second element of  2nd row: ', arr[1,1])

Second element of 1st row:  2
Second element of  2nd row:  5


In [19]:
# add the first element of row 1 and last element of 2nd row
arr = np.array([[1,2,3],[4,5,6]])
print('First element of 1st row: ', arr[0,0])
print('Last element of  2nd row: ', arr[1,2])
print('sum is: ',arr[0,0] + arr[1,2] )

First element of 1st row:  1
Last element of  2nd row:  6
sum is:  7


##### Accessing 3D Arrays

In [21]:
arr = np.array([[[1,2,3], [4,5,6], [6,7,8]]])
print(arr[0,2,2])

8


##### Slicing Arrays
- Slicing in python means taking elements from one given index to another given index.

- We pass slice instead of index like this: [start:end].

- We can also define the step, like this: [start:end:step]

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[::2])

[2 3 4 5]
[1 3 5 7]


In [7]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [10]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])


[7 8 9]


In [11]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
